### ISSUE TITLE
packing fraction usage

### ISSUE THREAD

**Issue by py1sl** [fusion-energy/neutronics_material_maker#19]
> This value is mutliplied by the density which allows packing_fraction to be taken into account for materials involving an amount of void. Recall that packing_fraction is equal to 1/void fraction

The documentation gives this statement for the packing_fraction parameter but it does not agree with the usage/output.
if I have 10 % void in a material 1/10 = 0.1 and the material density is multiplied by this to be an order of magnitude lower not 90% of the density which is the intention.  Using a number greater than 1 gives an error.
Should the correct definition not be packing_fraction = 1 - void fraction

Also when using with material.from_mixture if the fractions of the materials do not add to 1 there is a warning, but not if packing_fraction is also used, the resulting density is adjusted for both the remaining fraction and the packing fraction. I believe the warning should be still displayed.

**Comment by shimwell** [comment]
Thanks for reporting this,

I guess we can change 
```Recall that packing_fraction is equal to 1/void fraction```
to
```
Recall that packing_fraction = 1 - void fraction
```

**Comment by shimwell** [comment]
For an additional warning we can add to this section
https://github.com/fusion-energy/neutronics_material_maker/blob/a166ccebdb4949c987df75a404eaf8f63853e2c4/neutronics_material_maker/material.py#L883-L888

Any recommendations for the condition to check or the text you would like.

Just to double check my understanding are you referring to the packing_fraction argument to the from_mixture function or the packing_fraction attribute that materials have.

**Comment by py1sl** [comment]
the docs point was about the packing_fraction attribute but the warning point is about the packing_fraction argument to the from_mixture function.
That warning is ok, it just gets suppressed or caught if there is also a packing_fraction argument

**Comment by py1sl** [comment]
I don't think that is right,  
something like sum(fracs) + (1-packing_fraction) !=1.0
otherwsie when the fracs do add to 1 and you include a packing fraction it will be a warning.  
really you only want a warning when all volume(mass) is not accounted for

**Comment by py1sl** [comment]
combine them both i think is better still
sum(fracs)*packing_fraction + (1-packing_fraction) !=1.0

**Comment by shimwell** [comment]
Ah I've finally understood what you want
> really you only want a warning when all volume(mass) is not accounted for

I can make a PR for this

**Comment by shimwell** [comment]
fixed in #20 thanks for reporting @py1sl 

I'm closing this now as version 1.1.1 has been released with this correction
