### ISSUE TITLE
Density calculation for multipliers and breeders

### ISSUE THREAD

**Issue by generein** [fusion-energy/neutronics_material_maker#35]
The properties of some multipliers and breeders [here](https://github.com/fusion-energy/neutronics_material_maker/blob/main/src/neutronics_material_maker/data/multiplier_and_breeder_materials.json) is defined as temperature dependent, e.g. FLiBe:
`"density": "2.214 - 4.2e-4 * (temperature + 273.15)",`

However, given that the temperature is defined in Kelvin (and seemingly never converted to Celsius in the Material class), I believe these formulas should read `(temperature - 273.15)` if they are dependencies in Celsius. I can put a PR together if this is confirmed.

**Comment by shimwell** [comment]
Yes that looks like a good thing to fix, sorry about that. PR would be welcome @generein

**Comment by shimwell** [comment]
Fixed with PR #36 and a new version has been released with these changes

Many thanks
